import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  section: {
    padding: 20,
    backgroundColor: 'white',
    marginTop: 10,
    marginHorizontal: 10,
    borderRadius: 8,
  },
  settingsSection: {
    padding: 20,
    backgroundColor: '#f9f9f9',
    marginTop: 10,
    marginHorizontal: 10,
    borderRadius: 8,
    borderLeftWidth: 4,
    borderLeftColor: '#007AFF',
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 14,
    color: '#666',
  },
  sectionTitle: {
    color: '#333',
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 12,
  },
  settingsSectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 16,
    color: '#007AFF',
  },
  settingSubsection: {
    marginBottom: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  subsectionTitle: {
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 12,
    color: '#333',
  },
  inputGroup: {
    marginBottom: 16,
  },
  inputLabel: {
    fontSize: 13,
    fontWeight: '500',
    color: '#333',
    marginBottom: 6,
  },
  sliderContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  numericInput: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    backgroundColor: 'white',
    color: '#333',
    width: 80,
  },
  rangeText: {
    fontSize: 12,
    color: '#666',
    fontWeight: '500',
  },
  textInput: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    backgroundColor: 'white',
    color: '#333',
  },
  radioGroup: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  radioOption: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  radioCircle: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 2,
    borderColor: '#999',
    marginRight: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  radioCircleSelected: {
    borderColor: '#007AFF',
  },
  radioInner: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#007AFF',
  },
  radioLabel: {
    fontSize: 13,
    color: '#333',
  },
  result: {
    fontSize: 13,
    color: '#333',
    fontFamily: 'Courier',
    backgroundColor: '#f9f9f9',
    padding: 12,
    borderRadius: 4,
  },
  buttonSpacer: {
    height: 12,
  },
  resultBox: {
    backgroundColor: '#f0f0f0',
    padding: 12,
    borderRadius: 4,
  },
  resultText: {
    color: '#333',
    fontSize: 12,
    fontFamily: 'Courier',
    marginBottom: 4,
  },
  info: {
    fontSize: 12,
    color: '#666',
    fontStyle: 'italic',
  },
  dimensionsBox: {
    backgroundColor: '#f0f0f0',
    padding: 12,
    borderRadius: 4,
    borderLeftWidth: 4,
    borderLeftColor: '#34C759',
  },
  dimensionLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#34C759',
    marginBottom: 6,
  },
  dimensionText: {
    fontSize: 11,
    fontFamily: 'Courier',
    color: '#333',
    marginBottom: 3,
  },
  tableRowHeader: {
    flexDirection: 'row',
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#ddd',
    backgroundColor: '#e9e9e9',
    borderTopLeftRadius: 4,
    borderTopRightRadius: 4,
  },
  tableRow: {
    flexDirection: 'row',
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#ddd',
  },
  tableCell: {
    flex: 1,
    fontSize: 11,
    fontFamily: 'Courier',
    color: '#333',
    paddingHorizontal: 6,
  },
  tableCellField: {
    flex: 3,
    fontSize: 11,
    fontFamily: 'Courier',
    color: '#333',
    paddingHorizontal: 6,
  },
  tableCellShort: {
    flex: 1,
    fontSize: 11,
    fontFamily: 'Courier',
    color: '#333',
    paddingHorizontal: 6,
  },
  tableHeaderCell: {
    fontWeight: '700',
    color: '#333',
  },
  tableCellLabel: {
    fontWeight: '600',
  },
  tableCellEncoded: {
    color: '#555',
  },
  compactGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  compactInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'white',
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: '#ddd',
    width: '48%',
    minWidth: 150,
  },
  compactLabel: {
    flex: 1,
    fontSize: 11,
    fontWeight: '500',
    color: '#333',
  },
  compactInput: {
    width: 50,
    textAlign: 'center',
    fontSize: 13,
    fontWeight: '600',
    color: '#007AFF',
    paddingVertical: 4,
    paddingHorizontal: 8,
    backgroundColor: '#f5f5f5',
    borderRadius: 4,
  },
  collapsibleHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    paddingHorizontal: 12,
    backgroundColor: '#f0f0f0',
    borderRadius: 6,
    marginTop: 8,
  },
  collapsibleTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
  },
  collapsibleIcon: {
    fontSize: 12,
    color: '#666',
  },
  summaryBox: {
    backgroundColor: '#f0f0f0',
    padding: 16,
    borderRadius: 8,
    borderLeftWidth: 4,
    borderLeftColor: '#007AFF',
  },
  summaryTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#333',
    marginBottom: 12,
  },
  summaryText: {
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 4,
    color: '#333',
  },
  testResultCard: {
    backgroundColor: 'white',
    borderRadius: 8,
    marginBottom: 12,
    borderLeftWidth: 4,
    overflow: 'hidden',
  },
  testResultHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 12,
  },
  testResultTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: '#333',
    flex: 1,
    marginRight: 8,
  },
  testResultDuration: {
    fontSize: 12,
    fontWeight: '500',
    color: '#666',
  },
  testResultDetails: {
    backgroundColor: '#f9f9f9',
    padding: 12,
    borderTopWidth: 1,
    borderTopColor: '#e0e0e0',
  },
  testResultDetail: {
    fontSize: 11,
    color: '#555',
    fontFamily: 'Courier',
    marginBottom: 6,
  },
  testResultError: {
    fontSize: 11,
    color: '#ef4444',
    fontFamily: 'Courier',
    marginBottom: 6,
    fontWeight: '600',
  },
});
