package com.paywallkit

val INITIALIZATION_ERROR = "INITIALIZATION_ERROR"
val NOT_INITIALIZED_ERROR = "NOT_INITIALIZED_ERROR"
val PAYWALL_DECIDER_FETCH_ERROR = "PAYWALL_DECIDER_FETCH_ERROR"
val INVALID_ARGUMENT_ERROR = "INVALID_ARGUMENT"
val DECISION_ERROR = "DECISION_ERROR"
val UPDATE_ERROR = "UPDATE_ERROR"
