name: Build - Paywall iOS XCFramework
on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

  pull_request:
    types: [closed]
    branches: [main]
    paths:
      - 'paywall/library/**'
      - '!paywall/library/README.md'
      - '!paywall/library/tools'


defaults:
  run:
    working-directory: paywall
jobs:
  build:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: macos-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '22'

      # - name: Setup Gradle
      #   uses: gradle/gradle-build-action@v2

      # - name: Generate XCFramework
      #   run: ./gradlew podPublishXCFramework

      - name: Zip XCFramework
        run: |
          cd library/build/cocoapods/publish/release && zip -r ${GITHUB_WORKSPACE}/Paywall.xcframework.zip ./file.xcframework

      - name: Upload XCFramework as artifact
        uses: actions/upload-artifact@v6
        with:
          name: paywall-ios-xcframework
          path: Paywall.xcframework.zip
          if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Download xcframework artifact
        uses: actions/download-artifact@v6
        with:
          name: paywall-ios-xcframework

      - name: Test download
        run: ls -la ${{ github.workspace }}/Paywall.xcframework.zip

      - name: Create GitHub release and attach xcframework
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.event.inputs.release_tag }} ${{ github.workspace }}/Paywall.xcframework.zip --title "${{ github.event.inputs.release_tag }}" --notes "Release notes" --draft --prerelease
