name: Build - Paywall iOS XCFramework
on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

  pull_request:
    types: [closed]
    branches: [main]
    paths:
      - 'paywall/library/**'
      - '!paywall/library/README.md'
      - '!paywall/library/tools'


defaults:
  run:
    working-directory: paywall
jobs:
  build:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '22'

      # - name: Setup Gradle
      #   uses: gradle/gradle-build-action@v2

      # - name: Generate XCFramework
      #   run: ./gradlew podPublishXCFramework

      - name: Upload XCFramework as artifact
        uses: actions/upload-artifact@v6
        with:
          name: paywall-ios-xcframework
          path: paywall/library/build/cocoapods/publish/release/Paywall.xcframework
          if-no-files-found: error


  package:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - id: artifact-download
        name: Download xcframework artifact
        uses: actions/download-artifact@v6
        with:
          name: paywall-ios-xcframework
          path: /tmp/artifacts
      
      - name: Zip XCFramework
        run: |
          pwd
          ls -ltr  ${GITHUB_WORKSPACE}
          ls -ltr ${{ steps.artifact-download.outputs.download-path }}
          zip -r Paywall.xcframework.zip ${{ steps.artifact-download.outputs.download-path }}/Paywall.xcframework
      # - name: Zip XCFramework
      #   run: |
      #     cd library/build/cocoapods/publish/release && zip -r ${GITHUB_WORKSPACE}/Paywall.xcframework.zip ./file.xcframework

      # - uses: swift-actions/setup-swift@v3
      - name: Compute XCFramework checksum
        id: xc-framework-checksum
        run: echo "checksum=ASDFGHJKL" >> $GITHUB_OUTPUT
        # run: checksum=$(swift package compute-checksum ${GITHUB_WORKSPACE}/Paywall.xcframework.zip); echo "checksum=$checksum" >> $GITHUB_OUTPUT

      - name: Print checksum
        run: |
          echo "XCFramework Checksum: ${{ steps.xc-framework-checksum.outputs.checksum }}"

      - name: Update Swift binary targets 
        run: |
          sed -i 's/\${RELEASE_TAG}/${{ github.event.inputs.release_tag }}/g' library/Package.swift
          sed -i 's/\${CHECKSUM}/${{ steps.xc-framework-checksum.outputs.checksum }}/g' library/Package.swift
          cat library/Package.swift


        # - uses: swift-actions/setup-swift@v3
      # - name: Compute XCFramework checksum
      #   id: xc-framework-checksum
      #   run: swift package compute-checksum ${GITHUB_WORKSPACE}/Paywall.xcframework.zip

      # - name: Upload XCFramework as artifact
      #   uses: actions/upload-artifact@v6
      #   with:
      #     name: paywall-ios-xcframework
      #     path: Paywall.xcframework.zip
      #     if-no-files-found: error

  # release:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v5
  #     - name: Download xcframework artifact
  #       uses: actions/download-artifact@v6
  #       with:
  #         name: paywall-ios-xcframework

  #     - name: Test download
  #       run: ls -la ${{ github.workspace }}/Paywall.xcframework.zip

  #     - name: Create GitHub release and attach xcframework
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       run: |
  #         gh release create ${{ github.event.inputs.release_tag }} ${{ github.workspace }}/Paywall.xcframework.zip --title "${{ github.event.inputs.release_tag }}" --notes "Release notes" --draft --prerelease
